FROM ioribranford/build-love-android:11.5-env

ENV LOVE_VERSION        "11.5a"
ENV LOVE_ANDROID_URL    https://github.com/love2d/love-android.git
ENV LOVE_ANDROID_DIR    /love-android

# clone repo
RUN git clone --recursive $LOVE_ANDROID_URL ${LOVE_ANDROID_DIR}
WORKDIR ${LOVE_ANDROID_DIR}
RUN git checkout $LOVE_VERSION

# build
RUN ./gradlew assemble bundle
COPY ./build-game.sh .

# to sign packages and zip debug symbols for the Play Store
COPY sign-releases.sh package-debug-symbols.sh app/build/

CMD ./build-game.sh
